# Generated by Django 4.2.5 on 2023-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0002_recipemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='recipe_viws_count',
            field=models.IntegerField(default=1),
        ),
    ]
