# Generated by Django 4.2.5 on 2023-10-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0005_alter_student_department_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='RecipyApp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentid', to='RecipyApp.studentid'),
        ),
    ]
