# Generated by Django 4.2.5 on 2023-10-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0006_alter_student_department_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
    ]
