# Generated by Django 4.2.5 on 2023-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
