# Generated by Django 4.2.6 on 2023-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0010_subject_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
