# Generated by Django 4.2.6 on 2023-11-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipyApp', '0011_student_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='recipe_viws_count',
        ),
    ]
