# Generated by Django 4.2.7 on 2023-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_blogmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
