# Generated by Django 4.2.5 on 2023-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
